# Generated by Django 4.0.1 on 2024-02-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Creditedfrom', models.CharField(max_length=100)),
                ('Bankdetails', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='RENTAL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rental'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.CharField(max_length=300)),
                ('Photo2', models.CharField(max_length=300)),
                ('Photo3', models.CharField(max_length=300)),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Msg', models.CharField(max_length=100)),
                ('LOGIN1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frmlog', to='myapp.login')),
                ('LOGIN2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolog', to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('SERVICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
